name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        site_env: ["user", "pro", "local"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Run build for user

        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_SITE_ENV: ${{ matrix.site_env }}
          NEXT_PUBLIC_LOCAL_ID: aviation
        run: |
          yarn clean
          yarn install --frozen-lockfile    
          yarn build
        shell: bash