name: Node.js CI

permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        site_env: ["user", "pro", "local"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Run build for ${{ matrix.site_env }}

        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_SITE_ENV: ${{ matrix.site_env }}
          NEXT_PUBLIC_LOCAL_ID: aviation
          NEXT_PUBLIC_WORDPRESS_URL: "https://dpla.wpengine.com"
          NEXT_PUBLIC_PRO_BASE_URL: "https://pro.dp.la"
          NEXT_PUBLIC_USER_BASE_URL: "https://dp.la"
        run: |
          yarn clean
          yarn install --frozen-lockfile    
          yarn build
        shell: bash