name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      #      - name: Install Yarn
      #        run: npm install -g yarn

      - name: Run build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          yarn install --frozen-lockfile    
          yarn run build
        shell: bash
